apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: vnu
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  selector:
    matchLabels:
      app: vnu
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: vnu
    spec:
      containers:
      - name: vnu
        image: gcr.io/passmarked/vnu:latest
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: vnu
  labels:
    app: vnu
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: vnu
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vnu
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: vnu
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20